### ISSUE TITLE
Images should have transparent backgrounds

### ISSUE THREAD

**Issue by buro9** [cloudflare/claire#33] opened 2016-03-03 09:45 UTC
Newer versions of Chrome show extensions outside of the address bar and in the browser chrome itself.

![claire](https://cloud.githubusercontent.com/assets/72949/13490425/579ad0be-e124-11e5-953d-df8645c1755c.png)

The white backgrounds that the images have today results in a very ugly Claire icon.

We should move to using transparent backgrounds for images so that it continues to look good in all versions of Chrome/Chromium across all operating systems and system chromes.

PS: I would do this myself, but you know... Linux + GIMP, these are the times I yearn for a system that has Adobe CS available to it.

**Comment by terinjokes** [comment] 2016-03-03 16:03
Duplicate of #29

**Closed by terinjokes** 2016-03-03 16:03 UTC
